services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: tournoipro-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tournoipro_db
      MYSQL_USER: tournoiuser
      MYSQL_PASSWORD: tournoipassword
    ports:
      - "3307:3306"  # Changed from 3306:3306 to avoid port conflict
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  app:
    build: .
    container_name: tournoipro-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tournoipro_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: tournoiuser
      SPRING_DATASOURCE_PASSWORD: tournoipassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data: